grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  volumes:
    - ./dist:/var/lib/grafana/plugins/emma-sensu-app
    - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
    - GF_INSTALL_PLUGINS=grafana-piechart-panel
