grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  volumes:
    - ./dist:/var/lib/grafana/plugins/grafana-sensu-app
    - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,briangann-datatable-panel,vonage-status-panel,grafana-polystat-panel
